[book]
authors = ["clearloop"]
language = "en"
multilingual = false
src = "src"
title = "Graph The Rainbow"

[build]
build-dir = "docs"
create-missing = false

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/udtrokia/Graph-The-Rainbow"